version: '3.8'
services:
  app:
    build: .
    ports:
      - "8081:8081"
    environment:
      SERVER_PORT: 8081
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: examples
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
    depends_on:
      - db

  db:
    image: postgres:12
    environment:
      POSTGRES_DB: examples
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
